name: publish of docker image

on: 
    push: 
        branches: ['master']
    
jobs:
    push-to-registry:
        name: Push Docker image to DockerHub
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Extract version
              id: meta
              uses: docker/metadata-action@v3
              with:
                    images: bit3down/testjavaapp     

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                    push: true
                    tags: ${{ secrets.DOCKER_USERNAME }}/testjavaapp:${{ steps.meta.outputs.tags }}
                    context: .
                    file: ./Dockerfile
